// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  // Basic validation: ensure variables exist and URL is http/https
  const missing = [
    ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
    ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
  ];

  if (missing.length > 0) {
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}.`;
    console.warn(`[Supabase] ${message} Supabase client will be disabled in the browser build.`);
    throw new Error(message);
  }

  try {
    // Validate URL format
    const parsed = new URL(SUPABASE_URL);
    if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
      throw new Error('Invalid protocol');
    }
  } catch (err) {
    const message = `Invalid SUPABASE_URL; must be a valid http(s) URL.`;
    console.warn(`[Supabase] ${message} Supabase client will be disabled in the browser build.`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

function createNoOpSupabaseClient() {
  const error = new Error('Supabase is not configured.');
  const noOpResponse = { data: null, error };
  const noOpSessionResponse = { data: { session: null }, error: null };
  const noOpPublicUrlResponse = { data: { publicUrl: '' }, error: null };

  const noOpQuery = new Proxy(() => noOpQuery, {
    get(_target, prop) {
      if (prop === 'then') {
        return (resolve: (value: any) => void) => resolve(noOpResponse);
      }
      if (prop === 'getPublicUrl') {
        return () => noOpPublicUrlResponse;
      }
      return () => noOpQuery;
    },
    apply() {
      return noOpQuery;
    },
  });

  const noOpAuth = {
    getSession: async () => noOpSessionResponse,
    onAuthStateChange: async () => ({ data: { subscription: { unsubscribe() {} } }, error: null }),
    signUp: async () => noOpResponse,
    signInWithPassword: async () => noOpResponse,
    signOut: async () => ({ data: null, error: null }),
  } as any;

  const noOpStorage = {
    from: () => noOpQuery,
  };

  return {
    auth: noOpAuth,
    from: () => noOpQuery,
    storage: noOpStorage,
  } as any;
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) {
      try {
        _supabase = createSupabaseClient();
      } catch (err) {
        console.warn('[Supabase] client not created:', err instanceof Error ? err.message : err);
        _supabase = createNoOpSupabaseClient() as any;
      }
    }

    return Reflect.get(_supabase as any, prop, receiver);
  },
});

